### ISSUE TITLE
configure my config file so only classes and functions are commented

### ISSUE THREAD

**Issue by mrcfschr** [p1va/dotnet-document#13]
Thank you for this cool tool!
Quick question:
I copied the default config file and modified it to disable commenting enum members.
```
enum_member:
  summary:
    template: The {name} {enum}
    new_line: true
  enabled: false
  required: false
```
using `dotnet document config` shows that the change has taken effect since the lines enabled and required are no longer printed:
```
enum_member:
  summary:
    template: The {name} {enum}
    new_line: true
default_member:
```
However, when I run `dotnet document apply`, my enum members are still being commented. I also tried this with the default_members properties etc. with the same result.
How do I have to configure my config file so only classes and functions are commented and the rest (e.g. enum members) are left alone?
